GAME OVER
chkpt:20 epoch: 0 loss: 0.1688047 LR: [0.001] step: 103 score: 190 best_score: 190
GAME OVER
chkpt:20 epoch: 1 loss: 0.0079025 LR: [0.001] step: 172 score: 600 best_score: 600
GAME OVER
chkpt:20 epoch: 2 loss: 0.0086099 LR: [0.001] step: 95 score: 210 best_score: 600
GAME OVER
chkpt:20 epoch: 3 loss: 0.0161983 LR: [0.001] step: 96 score: 330 best_score: 600
GAME OVER
chkpt:20 epoch: 4 loss: 0.0919175 LR: [0.001] step: 195 score: 370 best_score: 600
GAME OVER
chkpt:20 epoch: 5 loss: 0.0711569 LR: [0.001] step: 107 score: 360 best_score: 600
GAME OVER
GAME OVER
chkpt:20 epoch: 6 loss: 0.0510941 LR: [0.001] step: 165 score: 350 best_score: 600
GAME OVER
chkpt:20 epoch: 7 loss: 0.0759495 LR: [0.001] step: 163 score: 390 best_score: 600
GAME OVER
GAME OVER
chkpt:20 epoch: 8 loss: 0.1165185 LR: [0.001] step: 97 score: 360 best_score: 600
GAME OVER
chkpt:20 epoch: 9 loss: 0.0643812 LR: [0.001] step: 111 score: 380 best_score: 600
average score last 10 games: 354.0
GAME OVER
Traceback (most recent call last):
  File "c:\Users\Gilad\Markman Dropbox\Gilad Markman\Python\PacMan\PacMan\Trainer.py", line 188, in <module>
    main (chkpt)
  File "c:\Users\Gilad\Markman Dropbox\Gilad Markman\Python\PacMan\PacMan\Trainer.py", line 141, in main
    torch.save(buffer,bufferPath)
  File "C:\Users\Gilad\.virtualenvs\Space_Invaders-WdsSLu6i\Lib\site-packages\torch\serialization.py", line 849, in save
    with _open_zipfile_writer(f) as opened_zipfile:
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gilad\.virtualenvs\Space_Invaders-WdsSLu6i\Lib\site-packages\torch\serialization.py", line 716, in _open_zipfile_writer
    return container(name_or_buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gilad\.virtualenvs\Space_Invaders-WdsSLu6i\Lib\site-packages\torch\serialization.py", line 687, in __init__
    super().__init__(torch._C.PyTorchFileWriter(self.name))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: File Data/buffer2 cannot be opened.
